### ISSUE TITLE
Create the product model with the following fields

### ISSUE THREAD

**Issue by Ezugworie08** [DIM-Squad/Grace-Shopper#13]
title -> STRING, require, not null, not empty
slug -> STRING, required, not null, not empty, built off the `name` for great urls
description -> TEXT, not null
price -> DECIMAL, defaultValue -> 0.0
imageURL -> STRING, defaultValue
quantity -> INTEGER, default -> 0
availability -> ENUM ('available', 'out-of-stock')
size -> ENUM ('large', 'medium', 'small')

**Comment by dustinheestand** [comment]
I won't create "availability" as it is covered by the "quantity" field. i.e. if quantity is zero, availability is out of stock

**Comment by dustinheestand** [comment]
also no slug for now as products may have duplicate names!
